CREATE TABLE "Admin" ("id" TEXT NOT NULL PRIMARY KEY, "email" TEXT NOT NULL, "passwordHash" TEXT NOT NULL, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "Admin_email_key" ON "Admin"("email");
CREATE TABLE "Video" ("id" TEXT NOT NULL PRIMARY KEY, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "youtubeUrl" TEXT NOT NULL, "videoId" TEXT NOT NULL, "category" TEXT NOT NULL DEFAULT 'Comercial', "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL);
